### ISSUE TITLE
Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by ramyzeidan** [linjungz/chat-with-your-doc#12]
Hi, im trying to install this on centos7, im using python 3.10 im getting this on almost all requirements not just aiofiles...
ERROR: Could not find a version that satisfies the requirement aiofiles==23.1.0 (from versions: 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0)
ERROR: No matching distribution found for aiofiles==23.1.0
any idea what that is? 
btw it's working fine on my windows computer but not on my VPS :(

**Comment by linjungz** [comment]
My dev machine is running Ubuntu. Maybe you could give it a try? Some folks also mentioned dependency issue on centos.



发自我的iPhone


------------------ Original ------------------
From: Ramy Zeidan ***@***.***&gt;
Date: Mon,Jun 19,2023 8:19 AM
To: linjungz/chat-with-your-doc ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [linjungz/chat-with-your-doc] Could not find a version that satisfiesthe requirement (Issue #12)





 
Hi, im trying to install this on centos7, im using python 3.10 im getting this on almost all requirements not just aiofiles...
 ERROR: Could not find a version that satisfies the requirement aiofiles==23.1.0 (from versions: 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0)
 ERROR: No matching distribution found for aiofiles==23.1.0
 any idea what that is?
 btw it's working fine on my windows computer but not on my VPS :(

**Comment by ramyzeidan** [comment]
you're right most packages are not compatible with centos or debian, i installed ubunto 22.04 on a vps i have, works like a charm!
you're awesome thank you 🙏🏻

**Comment by linjungz** [comment]
Enjoy chatting :)



发自我的iPhone


------------------ Original ------------------
From: Ramy Zeidan ***@***.***&gt;
Date: Tue,Jun 20,2023 8:46 AM
To: linjungz/chat-with-your-doc ***@***.***&gt;
Cc: Randy Lin ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [linjungz/chat-with-your-doc] Could not find a version thatsatisfies the requirement (Issue #12)





 
you're right most packages are not compatible with centos or debian, i installed ubunto 22.04 on a vps i have, works like a charm!
 you're awesome thank you 🙏🏻
