### ISSUE TITLE
Texts could not be input after some talking 

### ISSUE THREAD

**Issue by kevinwang2k** [linjungz/chat-with-your-doc#14]
Message panel for inputting texts disappeared. And one button 'Error' displayed but could not be pressed.
What's the problem and how to fix it? 
Thanks a lot.
![1687851459877](https://github.com/linjungz/chat-with-your-doc/assets/35440938/274546c1-3d2d-4bbe-b63e-1eedc10f8c45)

**Comment by linjungz** [comment]
Could you check the error output in the terminal? 
You may need to refresh the browser to reset the status. But the chat history will be gone. Need to handle the exception here and graceful exit and reset the status.

**Comment by kevinwang2k** [comment]
Thanks for your answer. The reason is here. 
**
This model’s maximum context length is 8192 tokens. However, your messages resulted in 9837 tokens. Please reduce the length of the messages.
**
How can we fix it gracefully so that the use could keep the right context and continue to talk with chatGPT?

**Comment by linjungz** [comment]
Got it. I think I need to reduce the tokens sending to OpenAI just like this:
https://stackoverflow.com/questions/76451997/langchain-reduce-size-of-tokens-being-passed-to-openai

I may not be able to reproduce the bug. You may try to fix it here:
https://github.com/linjungz/chat-with-your-doc/blob/d23ae6a912f2a9eb29e247cf70a4a1735076bc7f/chatbot.py#L57C45-L57C45

And see if it works.

**Comment by linjungz** [comment]
Here's the explanation for arg max_tokens_limt for ConversationalRetrievalChain

https://github.com/hwchase17/langchain/blob/dd2a151543a8f44a25bfdd00134302d02b39c35a/langchain/chains/conversational_retrieval/base.py#L169-L170

**Comment by kevinwang2k** [comment]
I added as following screenshot. But it could not work. I still got the same issue.

![image](https://github.com/linjungz/chat-with-your-doc/assets/35440938/d865ac5f-f3e0-46cc-ac2a-9ffbf5003ef9)

**Comment by linjungz** [comment]
I see. 

This arg is to limit the size of return from the vector store. And the chat history will be combined with the referenced documents as the context for next question. So I think you could try to reduce the size of chat history:

https://github.com/linjungz/chat-with-your-doc/blob/d23ae6a912f2a9eb29e247cf70a4a1735076bc7f/chat_web.py#L70C30-L70C30

By default it's set to 4. I think you may try to reduce this number to 3 or 2. And see if it works.

Need a way to handle the token limit in a more graceful way. Maybe I should calculate the token for each referenced document plus the chat history and limit the final prompt that's sent to GPT

**Comment by linjungz** [comment]
I see. 

This arg is to limit the size of return from the vector store. And the chat history will be combined with the referenced documents as the context for next question. So I think you could try to reduce the size of chat history:

https://github.com/linjungz/chat-with-your-doc/blob/d23ae6a912f2a9eb29e247cf70a4a1735076bc7f/chat_web.py#L70C30-L70C30

By default it's set to 4. I think you may try to reduce this number to 3 or 2. And see if it works.

Need a way to handle the token limit in a more graceful way.

**Comment by kevinwang2k** [comment]
I am thinking about one thing. we could try to reduce both the return from vector database and the chat history. But it must exceed the upper limit at last after several chat. It looks like a paradox.

**Comment by linjungz** [comment]
No worry.  That's why I set the limit for chat history with MESSAGES_TO_REFERENCE. For each new question, It will only use latest 4 messages in the history. So that's why I suggest we reduce this number.

It's possible to compress the chat history by summarization. But some information could be lost.

**Comment by kevinwang2k** [comment]
2 works better than 3. But it makes chatGPT clumsy. :(

**Comment by linjungz** [comment]
That’s why we need higher token limit. Wait and soon we will have Azure to support got-3.5 for 16k token limit.

And just for curiosity, back to the chat history, is the answer very long? As the referenced documents has been restricted to 4000 tokens as you set the max_token_limits, the chat history is more than 4000 tokens?

BTW I want to double check that you're using the latest version:
https://github.com/linjungz/chat-with-your-doc/releases/tag/v0.2.1
"reduce token usage in chat history to avoid reaching token limit"

**Comment by duronxx** [comment]
嘿嘿，随便找了一个招股说明书，有700多页，他变笨了，19 珠海元麒投资有限公司

20 成都松齐明科技有限公司

21

珠海市鸿鑫瑞机械科技有限公 司

22 珠海市宏泰机械科技有限公司

珠海市椿田机械科技有限公司的全资子公司
Human: 请问实际控制人是谁？

> Finished chain.

> Finished chain.
Traceback (most recent call last):
  File "/data/.venv/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "/data/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1048, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/data/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/data/chat-with-your-doc/chat_web.py", line 89, in get_answer
    reference_html = f"""<details> <summary>Reference [{i+1}] <a href="" target="_blank">{os.path.basename(doc.metadata["source"])}  P{doc.metadata['page']+1}</a> </summary>\n"""
KeyError: 'page'
![image](https://github.com/linjungz/chat-with-your-doc/assets/33643555/13a28c93-eb23-4e8b-bdc9-2f5ca3af34d7)

**Comment by duronxx** [comment]
![image](https://github.com/linjungz/chat-with-your-doc/assets/33643555/6afce44a-236d-43e2-a0f7-f9ff42f2c642)
哈哈，用chatgpt把代码修改了一下，运行成功了。
这是修改的部分，
 for doc in result_source:
        reference_html = f"""<details> <summary>Reference [{i+1}]"""
        if "source" in doc.metadata and "page" in doc.metadata:
            reference_html += f""" <a href="" target="_blank">{os.path.basename(doc.metadata["source"])}  P{doc.metadata['page']+1}</a>"""

**Comment by linjungz** [comment]
> 嘿嘿，随便找了一个招股说明书，有700多页，他变笨了，19 珠海元麒投资有限公司
> 
> 20 成都松齐明科技有限公司
> 
> 21
> 
> 珠海市鸿鑫瑞机械科技有限公 司
> 
> 22 珠海市宏泰机械科技有限公司
> 
> 珠海市椿田机械科技有限公司的全资子公司 Human: 请问实际控制人是谁？
> 
> > Finished chain.
> 
> > Finished chain.
> > Traceback (most recent call last):
> > File "/data/.venv/lib/python3.10/site-packages/gradio/routes.py", line 414, in run_predict
> > output = await app.get_blocks().process_api(
> > File "/data/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1320, in process_api
> > result = await self.call_function(
> > File "/data/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1048, in call_function
> > prediction = await anyio.to_thread.run_sync(
> > File "/data/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
> > return await get_asynclib().run_sync_in_worker_thread(
> > File "/data/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
> > return await future
> > File "/data/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
> > result = context.run(func, *args)
> > File "/data/chat-with-your-doc/chat_web.py", line 89, in get_answer
> > reference_html = f""" Reference [{i+1}] {os.path.basename(doc.metadata["source"])}  P{doc.metadata['page']+1} \n"""
> > KeyError: 'page'
> > ![image](https://user-images.githubusercontent.com/33643555/250081393-13a28c93-eb23-4e8b-bdc9-2f5ca3af34d7.png)

这个报错已经不是超过 token limit 了， 而是返回的 reference document 里面没有 page 相关的信息。 
如前面所说，如果你已经使用了最新的版本，应该已经把chat history带上reference document的bug修复掉了。
所以想确认之前的你出现的 token limit 的问题，通过最新的版本是可以修复的对吗？

**Comment by linjungz** [comment]
> ![image](https://user-images.githubusercontent.com/33643555/250086159-6afce44a-236d-43e2-a0f7-f9ff42f2c642.png) 哈哈，用chatgpt把代码修改了一下，运行成功了。 这是修改的部分， for doc in result_source: reference_html = f"""
> 
> Reference [{i+1}]"""
> if "source" in doc.metadata and "page" in doc.metadata:
> reference_html += f""" {os.path.basename(doc.metadata["source"])} P{doc.metadata['page']+1}"""

理解。这里就相当于跳掉显示参考文档的文件名和相关的页码。 但正常来讲这些信息应该在最开始注入 vector db 的时候会带上相关 metadata 的。你可以把这个PDF给我也试一试吗？我看看是哪里的问题
