### ISSUE TITLE
大佬，这个能不能每次上传都把文件的向量库存储起来，查找的时候可以查找历史的啊

### ISSUE THREAD

**Issue by chenkangck50** [linjungz/chat-with-your-doc#24]

**Comment by linjungz** [comment]
cli 有实现这个功能，但 web 目前没有，短期没暂时没有这个计划了

**Comment by linjungz** [comment]
我理解应该这个功能工作量不会太大，如果你有时间的话可以尝试一下，然后给个PR我合并进去 :)

**Comment by linjungz** [comment]
可以考虑利用 CLI 工具创建vector store, 在新版本的 WEB UI 中已支持选择已有的vector store #28
