### ISSUE TITLE
please suspend or takedown url phising use my brand

### ISSUE THREAD

**Issue by xxjefxx** [linjungz/chat-with-your-doc#25]
please delete or suspend or takedown this url https://waslot.azurefd.net/, because this url phising use my brand "waslot" and redirect to another brand. Please help me sir. thanks

https://github.com/linjungz/chat-with-your-doc/assets/140201955/ac95a5e0-7bc3-4f3d-b382-401c1251689d

**Comment by linjungz** [comment]
Hi, I don't use this url. You may turn to MS support for help. Thanks
