### ISSUE TITLE
bash: streamlit: command not found

### ISSUE THREAD

**Issue by dfmjndm** [linjungz/chat-with-your-doc#31]
I‘ve successfully install the streamlit but for convenience，I didn‘t create a new env.
Then I couldn't find the streamlit in my /usr/local/bin
The issue is similar to [link](https://discuss.streamlit.io/t/command-not-found/741/12)
I haven't solved it

**Comment by groundcat** [comment]
Perhaps you did not do `source .venv/bin/activate` after creating your new env?

```
python3 -m venv venv
source .venv/bin/activate

pip install streamlit
```

then check installed version

```
streamlit --version
```
