### ISSUE TITLE
Support for openai?

### ISSUE THREAD

**Issue by zxh263** [linjungz/chat-with-your-doc#9]
Support for openai?

**Comment by linjungz** [comment]
It should be trivial to support openai. I don’t have too much time devoting to this project recently. You’re welcome to submit a PR for this.



发自我的iPhone


------------------ Original ------------------
From: zxh263 ***@***.***&gt;
Date: Fri,Jun 16,2023 3:36 PM
To: linjungz/chat-with-your-doc ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [linjungz/chat-with-your-doc] Support for openai? (Issue #9)





 
Support for openai?
